### ISSUE TITLE
using nebula.field() on same page as sn-table makes table rendering unreliable

### ISSUE THREAD

**Issue by chadmoore** [qlik-oss/sn-table#488] opened 2022-03-23 20:48 UTC
If I add 4 nebula field lists to the same page as my sn-table, table doesn't render and I see this in console:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/230391/159792887-ac8ac057-fada-412c-8db9-dfe98a051880.png)

**Comment by LiKang6688** [comment] 2022-03-24 20:43
Hi @chadmoore, 
Try to update all @nebula.js related packages to the latest version.
Please let me know if it does not help.

**Comment by chadmoore** [comment] 2022-03-25 13:29
Unfortunately it seems this issue persists with v1.9.0

**Comment by LiKang6688** [comment] 2022-03-25 13:38
> Unfortunately it seems this issue persists with v1.9.0

Thank you for letting me know. Which version of the Qlik sense and the @nebula.js/stardust do you use?

**Comment by chadmoore** [comment] 2022-03-25 15:36
Qlik Sense Enterprise Aug 2021 - 14.28.3
@nebula.js/stardust - v2.6.1

**Comment by chadmoore** [comment] 2022-03-25 15:42
The issue persists w/ QSE Aug 2021 & stardust v2.8.0

**Comment by LiKang6688** [comment] 2022-03-25 16:17
> The issue persists w/ QSE Aug 2021 & stardust v2.8.0

Thanks. We gonna look into this and reply back to you soon.

**Comment by LiKang6688** [comment] 2022-03-28 17:39
Hey @chadmoore, I had a test with Aug 2021 QSEfW and cannot reproduce your issue. Please have a look at my test code https://github.com/qlik-oss/sn-table/tree/mashup/QSEfW/mashup-example/using-build-tool/qlik-sense-enterprise and feel free to do changes based on my branch.

**Comment by haxxmaxx** [comment] 2022-05-12 11:08
Hi @chadmoore. Since we can't reproduce this bug, we will close it unless additional information is provided

**Closed** 2022-05-19 13:59 UTC
Labels: bug, needs information, can't reproduce
